### ISSUE TITLE
Dynamic Allocation

### ISSUE THREAD

**Issue by obsidiangroup** [pabloromeo/clusterplex#120]
Clusterplex is a great project just from reading the documentation.  Wouldn't it be great if there was a mechanism to automatically deploy new workers as needed and destroy when not needed.  This would allow, once we reach a certain number of tasks per worker a new worker is deployed.  There could be some default settings like 

> DEFAULT_WORKERS - Minimal  amount of workers to start
> MAX_JOBS_WORKER - Maximum number of sessions per node that can be overwritten by node

Then, each node if they can support more or less the global MAX_JOBS_WORK then
> NODE_JOBS_WORKER - Specific node maximum jobs

Then, the orchestrator can keep track of tasks on each node, and when a certain treshold has been met, jobs will not be sent to that node, and when the overall threshold of all nodes has been met, a new worker is spawned.  This worker, once demand has went below threshold, would be killed.

THis could be as easy as increasing the number of deployed instances of a specific service.  The start-up commands for the new services would be configured and used.

**Comment by pabloromeo** [comment]
Thanks for the your comments :)
Yeah, and it is an interesting concept to think about.
However, a few things to consider: This was initially intended to run in a Container Orchestrator, such as Kubernetes or Swarm, which already manage service replicas. And keeping it agnostic of which platform you are running it on was also desired. Clusterplex doesn't actually know if you are running it in one or the other, or none, as standalone applications.

The orchestrator exposes task metrics for Prometheus and Grafana, which ultimately could be plugged in to logic for autoscaling Workers if you like, but having the orchestrator itself do the autoscaling would mean specific logic for K8s, or Swarm or whichever other option out there is being used to run it (others run the workers as standaone containers and not in an orchestrator, for example).
Meaning, the part that concerns me is where you say "a new worker is spawned". Given that they aren't an actual process that gets manually executed here, it's a container managed by a ReplicaSet in k8s or a Service in Swarm. 
Applications don't usually scale themselves up or down, an Autoscaler working with the orchestrator usually does that on a case by case basis.

For example, if running on K8s, you could define your autoscaling strategy in KEDA tied to a prometheus query (https://devtron.ai/blog/prometheus/).

Or a homegrown version could be a nodered automation monitoring those prometheus metrics and scaling a Swarm service using the contrib-dockerode extension to ensure there are always idle workers if that's desired, or scale them to down to 1 when no tasks are running.

I'm just mentioning examples to point out the difference in what "scaling" would mean under each different type of physical infrastructure and each user's scenario. In K8s you'd need to update the replicas through it's api or a kubectl command somewhere, in Swarm you'd need to run on a manager node and issue a command through the docker socket to scale the service, and it you're running standalone workers then that might mean to create a new container, if you used docker-compose it would be increasing the replica count, you sort of start getting into Container Orchestrator territory there and things can get messy fast.
That's why it was left out. So each person using it can decide their own scaling approach as needed. Some users might need to scale up on down based on a schedule, others based on usage, others might not be able to scale at all and just have them running idle (since it consumes nearly no resources when not transcoding), etc.

**Comment by pabloromeo** [comment]
One other thing that I just remembered :), I believe https://github.com/munnerz/kube-plex sort of behaves the way you mentioned, by creating pods when transcoding jobs are needed which later get destroyed when done. 
But, as mentioned before, that is a k8s solution only. I've never used it, and I'm not sure the wait times you might have waiting for pods to start before you start viewing your content.
That's why here we went with a simpler approch of having workers ready to receive requests, and leaving the scaling to external autoscalers.

**Comment by obsidiangroup** [comment]
> Meaning, the part that concerns me is where you say "a new worker is spawned". Given that they aren't an actual process that gets manually executed here, it's a container managed by a ReplicaSet in k8s or a Service in Swarm.
> Applications don't usually scale themselves up or down, an Autoscaler working with the orchestrator usually does that on a case by case basis.
