### ISSUE TITLE
workers getting 404 when downloading codecs

### ISSUE THREAD

**Issue by RobertHolstein** [pabloromeo/clusterplex#124]
My workers are getting a 404 when trying to download the codecs.

I did make sure my workers were able to get to the internet:
`root@plex-worker-docker2:/# wget google.com
--2022-03-21 17:08:44--  http://google.com/
Resolving google.com (google.com)... 74.125.21.139, 74.125.21.101, 74.125.21.138, ...
Connecting to google.com (google.com)|74.125.21.139|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2022-03-21 17:08:44--  http://www.google.com/
Resolving www.google.com (www.google.com)... 172.217.164.68, 2607:f8b0:4002:815::2004
Connecting to www.google.com (www.google.com)|172.217.164.68|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’` 

Worker logs:
[_plex_plex-worker.yiwdx3jmyl9ltwrobwnc6ttgg.2vvb3kyfzlcqfwksj1boktur4_logs.txt](https://github.com/pabloromeo/clusterplex/files/8319279/_plex_plex-worker.yiwdx3jmyl9ltwrobwnc6ttgg.2vvb3kyfzlcqfwksj1boktur4_logs.txt)

When trying to manually download the link (https://downloads.plex.tv/codecs//linux-x86_64-standard/libxbin_decoder.so) I get page not found and redirected to https://www.plex.tv/media-server-downloads/

**Comment by pabloromeo** [comment]
By looking at the URL that is being downloaded you might notice there is a double forward-slash in there. That's because in the worker start script ([start.sh](https://github.com/pabloromeo/clusterplex/blob/master/worker/app/start.sh)) is not able to extract the CODEC versions to download from the Plex binary, using the "strings" command.
`CLUSTERPLEX_PLEX_CODECS_VERSION=$(strings "Plex Transcoder" | grep -Po '[0-9a-f]{7}-[0-9]{4}$')`

How are you running the Worker? As a dockermod?
Also, when the container is starting up the logs are actually longer than the one you pasted, and it echoes out additional information that might help in determinining what's going on.

**Comment by RobertHolstein** [comment]
That worked! Thanks! YOUDABOMB!
