### ISSUE TITLE
force certain IP to certain worker and vise versa

### ISSUE THREAD

**Issue by thecoolreaver** [pabloromeo/clusterplex#145]
I am looking at this project as a alt from Unicorn Transcoder. I had to modify code to allow me to set when certain IPs play content, it would go to certain transcoders/workers. This was done as my main server is in a datacenter but I have a copy of all the content locally at home and have a small system that transcodes locally instead of pulling from the internet.

Reviewing the code, I wouldn't know where to start or if this is possible but I am asking here to see if it be possible to build but based on the style I am not sure?

**Comment by pabloromeo** [comment]
Ah, I see. 
Now, I think there are a few differences with how Unicorn works, in this case. AFAIK, in Unicorn the client is forwarded to the worker and streams directly from there. Clusterplex works a bit differently. The transcode job is offloaded to the worker, but the content is streamed by Plex. 
If in your case when you mention main server you are referrin to PMS, then it might not be ideal since the content would still be streamed through your datacenter, yet transcoded locally. In the case of Clusterplex workers don't have a copy of the content, they actually access the central content through a network share shared by all.

**Comment by obsidiangroup** [comment]
Would it be possible for ClusterPlex to stream the content instead of having Plex handle it? If the workers have access to the media, then couldn't ClusterPlex handle all the heavy lifting?

**Comment by pabloromeo** [comment]
It would probably be possible, but it would require a considerable rearchitecture of how all of this works, I think. You'd probably need an architecture more similar to unicorn transcoder, where Plex redirects all traffic to workers directly. Not sure how they implement the actual streaming and have support for the different streaming mechanisms Plex clients use.
