### ISSUE TITLE
Secured connection

### ISSUE THREAD

**Issue by flopon** [pabloromeo/clusterplex#149]
First of all, thank you for your project, it's an improvement for my plex server that I was waiting for a long time.
I have been able to dispatch transcoding between 3 node, with VAAPI HW transcoding working.

My only concern is something not in your documentation, and discovered during my tests : It seems we need to accept unsecured connection to our server to permit the worker to communicate with it.
Maybe it's something you could improve ?

I also saw that you were testing a stream splitting feature. Have you had success in this way? That would be really great.

Thank you again and congratulations for this project.

**Comment by pabloromeo** [comment]
Hi!
Thanks for your comments! Glad it's working and with HW transcoding. Excellent news!

Regarding your comment about the unsecure connections, you mean the need for adding the worker ip range under "List of IP addresses and networks that are allowed without auth", correct?
I believe that one is related to how the Plex Transcoder works. What it does, during the transcode, is periodically hit a specific URL where it posts the session transcoding progress. It appears that Plex blocks any requests that don't come from localhost or from IPs in that list.
I'm thinking that there may be a workaroud, but it might mean adding more components to the mix:
Just thinking off the top of my head, if we were to have a small application bundled into the the PMS dockermod, which would start along with Plex and listen for http traffic on a specific port, we could probably use that as the target invoked by the workers instead of PMS directly, and then have THAT application repeat the same original request to Plex. I'm guessing Plex would let that request through. I'd have to test that out, but it might work, and it would remove that requirement for unauthenticated access from specific IPs. I'll see if there's a simpler alternative too, just in case.
Are you currently using it through the Dockermod or using the custom docker image?

Great catch around Stream-Splitting. Unfortunately I never got it to work and it just remains in the backburner. I wanted to attempt splitting a single transcode request across distributed workers seamlessly but it turned out to be much more difficult than I initially thought. Since there's absolutely zero documentation on the different types of requests Plex might send, it's pretty much all trial and error and hoping for the best lol.

**Comment by flopon** [comment]
Hi,
Thank you for your quick response.

No I was talking about the "Secure connections" option, under "Network". Workers can only connect to the server if set to "Preferred". It was also mandatory to authorize the docker subnet, but it's clear in your documentation.

**Comment by flopon** [comment]
Hello again,

For your information, I changed the instruction ".replace('127.0.0.1:', `${PMS_IP}:`)" to ".replace('http://127.0.0.1:', `https://${PMS_IP}:`)" in your transcoder.js, and secured connection is now working.

If I remember well, plex now set up a default ssl certificate, so I think this modification can be done safely, as https endpoint will always be availlable for worker to report back.

Or we can add an env var switch to use secured connection ?

**Comment by pabloromeo** [comment]
That's a great test!
Yeah, I'm not sure how that would behave in cases where someone is using custom certificates and encryption keys. Let me think about it a minute and see if we can add an extra ENV var to enable the http -> https replacement, to avoid breaking other people's deployments but still add the functionality :)

**Comment by pabloromeo** [comment]
I finally was able to get around to it :)
I've added an environment variable called FORCE_HTTPS, to allow support for Secure Connections: https://github.com/pabloromeo/clusterplex/pull/160

It's included in Release https://github.com/pabloromeo/clusterplex/releases/tag/v1.3.15

**Comment by flopon** [comment]
Tested, perfectly working, thank you!
