### ISSUE TITLE
Kubernetes Helm Chart

### ISSUE THREAD

**Issue by AngellusMortis** [pabloromeo/clusterplex#156]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It would be great to have a Helm Chart to be able to install the cluster on a Kubernetes cluster. 

**Describe alternatives you've considered**

There could be raw docs on how to install on a Kubernetes cluster as a starting point, but Docker Swarm is not really a viable alternative when you are running a cluster.

**Comment by pabloromeo** [comment]
That would be awesome!! I don't have a k8s cluster at hand at the moment to create working deployment examples or a Helm Chart and test it out.
It would be very cool if some of the others users already running it in k8s could provide some samples, either within this repo or on their own github repos.

**Comment by pabloromeo** [comment]
FYI, I finally got around to setting up a k3s cluster, so I'll soon be sharing example k8s manifests for setting it all up.

**Comment by brandan-schmitz** [comment]
I have consolidated the manifests I use to deploy my instance of ClusterPlex into a single file with some commented section and notes on deployment. As of this comment it is configured to use the latest 1.3.17 release that includes the support for the EAE workers. Please read my comment in the GIST if you are going to use this for more information. This should help people who want to get started while something more official is created.

https://gist.github.com/brandan-schmitz/7f775e30c17022caf62e3cccb5c07606

@pabloromeo I have lots of experience with K8s and creating helm charts if you would like me to take a stab at it I sure can.

**Comment by pabloromeo** [comment]
@brandan-schmitz oh, help with the creation of a helm chart would be amazing! 
I've mostly just used Helm as end user, never attempted to create something elaborate or highly configurable for others.
Yeah, feel free to take a stab at it, I'm sure it'll be useful to everyone!

Regarding the PMS_IP issue, yeah, it's kind of annoying that plex isn't too happy with progressUrl calls coming from nodes others than itself.
I've been thinking of alternatives around this, to avoid the need for the configuration or subnets or allowing access without auth in Plex. Maybe a tiny proxy deployed as a sidecar on PMS or something like that. Gotta do a few tests to see what's viable.

**Comment by pabloromeo** [comment]
FYI the new v1.4.0 release just added some very interesting stuff I think.

The new local relay means there is no longer a need for setting up the subnet or ips of workers to be allowed without Auth, it also allows us to use plex's service name instead of using the PMS_IP and simplifies config for secured connections, and there's no need now to be sharing /tmp, just /transcode.

I've also reorganized the documentation and provided an example manifest of running it on k8s (this one is a mix between @brandan-schmitz and my own setup which uses a replicaSet instead of a deployment for workers).

Documentation is now a bit more clear about data sharing and the readwritemany volumes.

**Comment by brandan-schmitz** [comment]
Nice work @pabloromeo the proxy is a great idea to solve the issue with the service names. I was going to look at working on a helm chart sometime this week so this timing is perfect.

**Comment by brandan-schmitz** [comment]
@pabloromeo I know it has been some time since this was closed as stale, but I managed to finally get around to creating a helm chart for ClusterPlex that I use in my cluster. It is very configurable with appropriate stuff for each component as well as easily allowing the creation of the proper shared storage volumes. Please see pull request #222

**Comment by pabloromeo** [comment]
That's awesome @brandan-schmitz!! I'll take a look and merge, I'm sure it will be useful to others.
