### ISSUE TITLE
clusterplex_worker_dockermod ARM

### ISSUE THREAD

**Issue by RuiSMagalhaes** [pabloromeo/clusterplex#227]
👋 

Amazing project here 🎉 

**REQUEST**
- ghcr.io/pabloromeo/clusterplex_worker_dockermod is only available for AMD64 and not ARM. 
Could we have the ARM version too?

I can open a PR too if someone point me to the right direction (may I change the gh workflow to include ARM version too? )

**Comment by pabloromeo** [comment]
Hi!
If I'm not mistaken linuxserver dockermods don't actually need to be multi-arch, since they are basically just a transport for scripts and files that the linuxserver base image later incorporates during startup and executes for the actual install on the already running container (which will be running in the proper arch already). 
It's not actually a container that is started, AFAIK. But I could be wrong.
Try to run it and see if you encounter issues, but if I remember correctly I've also run these mods on ARM without issues.

**Comment by pabloromeo** [comment]
@RuiSMagalhaes were you able to run it?

**Comment by RuiSMagalhaes** [comment]
👋 

Before you answered the first time I ran it with the Custom Docker images - meaning using `ghcr.io/pabloromeo/clusterplex_pms:latest` and `ghcr.io/pabloromeo/clusterplex_worker:latest`.

Since it worked I didn't try it with the dockermods.

**Comment by pabloromeo** [comment]
Ah! Glad to hear! 👍
