### ISSUE TITLE
Clusterplex with docker but without swarm or kubernetes?

### ISSUE THREAD

**Issue by Azathoth88** [pabloromeo/clusterplex#258]
A short question: Is it possible to use Clusterplex WITHOUT Docker Swarm or Kubernetes?

Background: I have a Synology NAS.
Docker Swarm is currently not working (Broke Synology). 

So the question: Is it possible to use Clusterplex manually in docker?
So with a "simple" docker-compose?

**Comment by pabloromeo** [comment]
Sure!
The only real requirements are docker and having a shared network location for transcoding.
Some environment variables might be slightly different, such as for example the PMS_IP instead of relying on service names (which wouldn't be available without a orchestrator) but just plain docker compose on different physical machines should work.
