### ISSUE TITLE
Update clusterplex_pms Image to plex version 1.40.3.8555

### ISSUE THREAD

**Issue by Azathoth88** [pabloromeo/clusterplex#315]
Hello,

Thank you for your great project. It took me some time to be able to realise it. Swarm & Co. were completely new territory for me. But I managed it in the end. Unfortunately, it doesn't work for me with the DockerMods, but I had to fall back on the ClusterPlex image.

Version 1.40.2.8395 is currently running on my server. Version 1.40.3.8555 is displayed as an update. Can you provide an updated image?

**Comment by pabloromeo** [comment]
Hi! Glad you got it to work.
Odd that it didn't work with the dockermods, since it's actually the same code in both, just different packaging.

Regarding the updates, if I remember correctly the latest tag gets built nightly so it should be up to date with plex.
You have a few options regarding swarm on how to keep them up to date.
I believe you can have your docker-compose.yaml specify you want to always pull the latest image on startup. So if you do that and restart the service it should run the latest.
Or you could run something like shepherd or https://github.com/shizunge/gantry and as a service in swarm and have it update other services automatically.
Sorry I can't be more exact right now, since I'm replying from my phone since I'm traveling, but next week I can look into how I used to run it on swarm back then, and help you set up automatic updates on services.

Other useful info here: https://www.reddit.com/r/docker/s/yCPjCtRTLY

**Comment by Azathoth88** [comment]
Hello, I actually know how to update containers. I have already deleted the service, deleted the images and reloaded them.
This is also possible with three clicks via Portainer.
I'm using latest tag from your images image: ghcr.io/pabloromeo/clusterplex_pms:latest)

The result is the same: The PMS is not up to date.
The inspect of the image shows the following:

![2024-06-17 14_12_56-Portainer _ Lokal – Opera](https://github.com/pabloromeo/clusterplex/assets/44654944/e2ffaa47-de9c-4530-b397-4c41de9b863c)

In my opinion, this version is hardcoded. When I look into your images:

![images](https://github.com/pabloromeo/clusterplex/assets/44654944/5a362ded-c1a3-42ee-a9fd-8a89eaf682d2)
sha256:ed8db3ec34b923ad6d52bf48df8579d27478453202a347d6c21acbfa28111835

its the same on my side:
ghcr.io/pabloromeo/clusterplex_pms:latest@sha256:ed8db3ec34b923ad6d52bf48df8579d27478453202a347d6c21acbfa28111835@sha256:d5450d37ee7f9f9f33b59f50837127aed93f310c3740d30693a60012865eac85


If I understand correctly, you are building on a Linux server image. Is it possible that your image is not based on the latest Linuxserver image?

**Comment by albertsj1** [comment]
@Azathoth88 Try pulling latest tag. It was updated yesterday and plex shows as updated to me.
