### ISSUE TITLE
Amazing! Requesting Live TV

### ISSUE THREAD

**Issue by buroa** [pabloromeo/clusterplex#32]
Currently Live TV fails to do a remote transcode so it is forced to transcode on the PMS.

Would love to be able to scale Live TV transcodes as this is the most used feature of my PMS.

**Comment by pabloromeo** [comment]
Great to hear! :)
Unfortunately I don't have LiveTV in my setup, in order to be able to test it.
Did you see any relevant info in the worker logs or in Plex's debug logs?
I would have expected it to work, given that we don't actually mess too much with Plex's arguments or anything like that, which is why features like Optimization/Conversion work OOTB as well. 
Plex might be doing something differently with LiveTV transcodes.

**Comment by pabloromeo** [comment]
So, I finally did have a bit of time to test. Unfortunately only using xTeVe (https://github.com/xteve-project/xTeVe) since I don't have Live TV going through Plex.
In the case of xTeVe, the default configuration of having Plex going direct to the Streaming Service did fail, for unkown reasons at the moment. Transcoding was ocurring on the Worker, but Plex wouldn't pick up the segments and begin streaming.
However, enabling the "Streaming Buffer" option in xTeVe's Settings, so that xTeVe becomes a buffer middleman for the content, did work. Remote transcoding kicked-off as expected and Plex was able to stream the content.

**Comment by buroa** [comment]
This seems work now. Let's close this :)
