### ISSUE TITLE
JS Error in Worker Logs when transcoding VAAPI (Intel iGPU Cluster)

### ISSUE THREAD

**Issue by ajax-lives** [pabloromeo/clusterplex#93]
Hey there!  Awesome software and work, looks extremely promising!
I'm getting an error when transcoding VAAPI (viewed in worker logs).
I'm not a very efficient JS dev, so I'm not entirely sure what it's about.
Any help is appreciated!  This is the only clustering project I could find for Plex, so I'm very hopeful!

```
Orchestrator notified
Removing process from taskMap
Received task request
Setting hwaccel to VAAPI
Transcoding failed:
Error: spawn /usr/lib/plexmediaserver/Plex Transcoder ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /usr/lib/plexmediaserver/Plex Transcoder',
  path: '/usr/lib/plexmediaserver/Plex Transcoder',
  spawnargs: [
    '-hwaccel',
    'VAAPI',
    '-codec:0',
    'hevc',
    '-codec:1',
    'ac3',
    '-analyzeduration',
    '20000000',
```

**Comment by pabloromeo** [comment]
Hi!
Ah, so for hardware transcoding I believe you may need additional steps.
For example, mounting the proper dev/dri, as described here: https://docs.linuxserver.io/images/docker-plex#hardware-acceleration

Now, AFAIK (I could be wrong), Docker Swarm does not support mounting devices yet, so you may have to run the worker as a standalone container outside of swarm for it to be able to use VAAPI.

There was also a PR which added support for overriding the transcoder inferred by Plex (since PMS may have different hardware than the worker). More details on it here:
https://github.com/pabloromeo/clusterplex/pull/81

**Comment by pabloromeo** [comment]
@ajax-lives any luck with this?

**Comment by ajax-lives** [comment]
Hey there!  I gave up before you responded.  I think I spent about 12 hours or so, testing different things.  The only result I was able to produce was either errors (of variety), or Plex would completely ignore the workers, and run on its own.

**Comment by ajax-lives** [comment]
I wasn't using Docker Swarm, I was running Docker on 1 VPS, and 4 dedicated servers, on an internal network.  I was using the latest version at the time, which would've included https://github.com/pabloromeo/clusterplex/pull/81 if that's correct?

**Comment by pabloromeo** [comment]
Ah, I'm sorry about it not working out.
I know others do run it standalone outside of Swarm or Kubernetes, but their setups aren't documented yet, except on closed issued were any problems were resolved.
I've recently added further instructions around the "List of IP addresses and networks that are allowed without auth" which is also necessary for workers to be able to report progress back. Not sure if it was related to this issue.

Thanks for replying. I'm gonna close this issue, and if you ever want to give it a shot again we can troubleshoot on a new one.
